FROM nvcr.io/nvidia/deepstream:7.0-triton-multiarch

# Install python dependencies
RUN bash /opt/nvidia/deepstream/deepstream/user_deepstream_python_apps_install.sh --version 1.1.11

WORKDIR /workspace
